#!/bin/bash
sqlfluff --version

export TIMEOUT="${TIMEOUT:-2h}"
export TIMEOUT_HARD="${TIMEOUT_HARD:-10m}"

if [ $# -eq 0 ]; then
    timeout -k "$TIMEOUT_HARD" "$TIMEOUT" sqlfluff lint --dialect oracle --disable_progress_bar
else
    case $1 in
    ansi | bigquery | exasol | hive | mysql | oracle | postgres | redshift | snowflake | spark3 | sqlite | teradata | tsql)
        if [ $# -eq 1 ]; then
            timeout -k "$TIMEOUT_HARD" "$TIMEOUT" sqlfluff lint --dialect "$1" --disable_progress_bar
        else
            timeout -k "$TIMEOUT_HARD" "$TIMEOUT" sqlfluff lint --dialect "$1" --disable_progress_bar "${@:2}"
        fi
        ;;
    dialects) sqlfluff dialects ;;
    rules) sqlfluff rules ;;
    *) timeout -k "$TIMEOUT_HARD" "$TIMEOUT" sqlfluff lint --dialect oracle --disable_progress_bar "$@" ;;
    esac
fi
